name: dartnng
environment:
  sdk: ^2.17.1
dependencies:
  ffi: ^1.2.1
  path: ^1.8.1

dev_dependencies:
  ffigen: ^5.0.0
  msgpack_dart: ^1.0.0

ffigen:
    name: 'nng'
    description: 'Nanomsg NG bindings'
    output: 'lib/bindings.dart'
    headers:
        entry-points:
        - 'nng_inc.h'
    functions:
        symbol-address:
            include:
                - nng_close_ptr
